CMDSCRIPT /usr/lib/bedrock/handle-ups-event
PIPEFN /run/nut/upssched.pipe
LOCKFN /run/nut/upssched.lock
AT ONLINE * EXECUTE ONLINE
AT ONBATT * EXECUTE ONBATT
AT LOWBATT * EXECUTE LOWBATT
AT FSD * EXECUTE FSD
