[Unit]
After=bedrock-storage-activation.service
Requires=bedrock-storage-activation.service

[Service]
ExecStart=
ExecStart=/usr/sbin/smbd --foreground --no-process-group --configfile=/var/lib/bedrock/storage/services/smb.conf
ReadWritePaths=/var/lib/bedrock/storage/services
